### ISSUE TITLE
iOS SDK not compile with the latest Tetragon-mobile

### ISSUE THREAD

**Issue by da1ssk** [mapfit/iOS-sdk#2]
I added ```pod 'Mapfit'``` but it didn't build.
What worked was to add ```pod 'Tetragon-mobile', '1.2'```
Please fix it or add a note in readme.
Thanks!

**Comment by zainnadeem** [comment]
Hey @da1ssk,

Thank you for bringing this to our attention. We have updated the `pod 'Mapfit'`. Adding pod `'Tetragon-mobile', '1.2`' is no longer necessary. 

>
